apiVersion: v1
kind: Namespace
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    # This automatically activates Istio sidecar injection for all pods in the default namespace
    istio-injection: enabled
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: 'https://istio-release.storage.googleapis.com/charts'
    chart: base
    targetRevision: 1.24.0
  destination:
    server: 'https://default.svc'
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: 'https://istio-release.storage.googleapis.com/charts'
    chart: istiod
    targetRevision: 1.24.0
    helm:
      values: |
        meshConfig:
          accessLogFile: /dev/stdout
          enableAutoMtls: true
        pilot:
          autoscaleEnabled: true
          autoscaleMin: 2
          autoscaleMax: 5
  destination:
    server: 'https://default.svc'
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
